# Generated by Django 5.1.6 on 2025-03-06 13:50

import django.db.models.deletion
import times.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0018_cuaderno_apunte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=128)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=128)),
                ('biographics', models.TextField(default='This section needs to be expanded.')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='mlbTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('nomina', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('position', models.CharField(default='Not Specified', max_length=256)),
                ('number', models.IntegerField(default=0)),
                ('equ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.equipo')),
                ('jug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='LigaTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagActivo', models.BooleanField(default=True)),
                ('equipoRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.equipo')),
                ('ligaRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.liga')),
            ],
        ),
        migrations.CreateModel(
            name='mlbGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('local_runs', models.IntegerField()),
                ('visit_runa', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_team', to='times.mlbteam')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_team', to='times.mlbteam')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('terminado', models.BooleanField(blank=True, default=False, null=True)),
                ('fase', models.CharField(max_length=120)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.liga')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elocal', to='times.equipo')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evisita', to='times.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='matchSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Goles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('adicional', models.IntegerField()),
                ('penal', models.BooleanField()),
                ('penales', models.BooleanField()),
                ('og', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.contrato')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.TextField()),
                ('minuto', models.IntegerField(default=0)),
                ('tipo', models.IntegerField(default=0)),
                ('comm_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Penales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado', models.IntegerField()),
                ('anotado', models.BooleanField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.contrato')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='squadPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.contrato')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.matchsquad')),
            ],
        ),
    ]
