# Generated by Django 5.1.6 on 2025-03-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0020_cuenta_trxtyp_trx_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApunteConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('media_type', models.CharField(max_length=100)),
                ('unidades', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('apunte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.apunte')),
            ],
        ),
    ]
