# Generated by Django 5.1.6 on 2025-04-05 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0022_tweet_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
    ]
