# Generated by Django 5.1.6 on 2025-04-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0023_bookentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
