# Generated by Django 5.1.6 on 2025-05-15 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0024_booklist_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
