# Generated by Django 5.1.6 on 2025-05-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0025_tweet_updated_at_alter_tweet_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=512)),
                ('groupinfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookGroupEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.bookentity')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.bookentitygroup')),
            ],
        ),
    ]
