# Generated by Django 5.1.6 on 2025-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0026_bookentitygroup_bookgroupentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookentity',
            name='importancia',
            field=models.IntegerField(default=50),
        ),
    ]
